/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


export const updatePantryBody = zod.object({
  "id": zod.number().optional(),
  "user": zod.object({
  "id": zod.uuid().optional(),
  "email": zod.string().optional()
}).optional(),
  "ingredients": zod.array(zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional()
})).optional()
})

