/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  useCallback
} from 'react';

import type {
  PantryDTO
} from '../../model';

import { useCustomFetch } from '../../../utils/customFetch';




export const useGetPantryByUserIdHook = () => {
        const getPantryByUserId = useCustomFetch<PantryDTO>();

        return useCallback((
    
 signal?: AbortSignal
) => {
        return getPantryByUserId(
          {url: `http://localhost:1291/pantry`, method: 'GET', signal
    },
          );
        }, [getPantryByUserId])
      }
    

export const getGetPantryByUserIdQueryKey = () => {
    return [`http://localhost:1291/pantry`] as const;
    }

    
export const useGetPantryByUserIdQueryOptions = <TData = Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPantryByUserIdQueryKey();

  const getPantryByUserId =  useGetPantryByUserIdHook();

    const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>> = ({ signal }) => getPantryByUserId(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPantryByUserIdQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>>
export type GetPantryByUserIdQueryError = unknown


export function useGetPantryByUserId<TData = Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPantryByUserId<TData = Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPantryByUserId<TData = Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPantryByUserId<TData = Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetPantryByUserIdHook>>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = useGetPantryByUserIdQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const useUpdatePantryHook = () => {
        const updatePantry = useCustomFetch<PantryDTO>();

        return useCallback((
    pantryDTO: PantryDTO,
 ) => {
        return updatePantry(
          {url: `http://localhost:1291/pantry`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: pantryDTO
    },
          );
        }, [updatePantry])
      }
    


export const useUpdatePantryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>, TError,{data: PantryDTO}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>, TError,{data: PantryDTO}, TContext> => {

const mutationKey = ['updatePantry'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      const updatePantry =  useUpdatePantryHook()


      const mutationFn: MutationFunction<Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>, {data: PantryDTO}> = (props) => {
          const {data} = props ?? {};

          return  updatePantry(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePantryMutationResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>>
    export type UpdatePantryMutationBody = PantryDTO
    export type UpdatePantryMutationError = unknown

    export const useUpdatePantry = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>, TError,{data: PantryDTO}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<ReturnType<typeof useUpdatePantryHook>>>,
        TError,
        {data: PantryDTO},
        TContext
      > => {

      const mutationOptions = useUpdatePantryMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    