/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


export const createUserBody = zod.object({
  "id": zod.uuid().optional(),
  "email": zod.string().optional()
})

