/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  z as zod
} from 'zod';


/**
 * Returns an ingredient by its unique identifier
 * @summary Get ingredient by ID
 */
export const getIngredientByIdParams = zod.object({
  "ingredient_id": zod.number()
})

/**
 * Updates an existing ingredient by its ID and returns the updated ingredient
 * @summary Update an existing ingredient
 */
export const updateIngredientParams = zod.object({
  "ingredient_id": zod.number()
})

export const updateIngredientBody = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional()
})

/**
 * Deletes an ingredient by its ID and returns a success message
 * @summary Delete an ingredient
 */
export const deleteIngredientParams = zod.object({
  "ingredient_id": zod.number()
})

/**
 * Creates a new ingredient and returns the created ingredient
 * @summary Create a new ingredient
 */
export const createIngredientBody = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional()
})

