/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RecipeDTO } from './recipeDTO';

export type GetAllRecipes200 = {[key: string]: RecipeDTO[]};
