/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDTO } from './userDTO';
import type { IngredientDTO } from './ingredientDTO';

export interface PantryDTO {
  id?: number;
  user?: UserDTO;
  ingredients?: IngredientDTO[];
}
